In [1]:
pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
# Thu vien can thiet
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib
matplotlib.rcParams["figure.figsize"] = (20,10)

<h1> PART 1: DATA CLEANING <h1>

In [4]:
df = pd.read_csv("dataIQIYI.csv")
df.head()

movie_title     kind  number_of_rating  \
0                 Mật Tình Thất Tâm Phần 1  Phim bộ             14000   
1  【Lồng Tiếng】Cửa Hàng Tiện Lợi Saet Byul  Phim bộ              1600   
2                        Sắc Xanh Lãng Mạn  Phim bộ              4800   
3                    Quy Lộ (Đường Về Nhà)  Phim bộ             56800   
4                         Đời Sống Ngục Tù  Phim bộ              8900   

   rating_score classification  release_year  duration             country  \
0           8.4            T13          2018        12  Trung Quốc đại lục   
1           9.4            T13          2020        16            Hàn Quốc   
2           9.3            T16          2020        14            Thái Lan   
3           9.7            T13          2023        30  Trung Quốc đại lục   
4           9.6            T18          2017        16            Hàn Quốc   

                                               genre            director  \
0   Lãng Mạn, Tổng Tài Bá Đạo, Thành Thị, Thanh Xuân       Zhang Lu Quan   
1        Lãng Mạn, Thành Thị, Thanh Xuân, Tiếng Việt       Myung-woo Lee   
2  Tội Phạm, Kinh Dị, Hình Sự, Tình Bạn, Thanh Xu...  Ongart Singlumpong   
3  Lãng Mạn, Thành Thị, Hôn Nhân, Tiếng Phổ Thông...          Yu Cui Hua   
4  Tội Phạm, Tình Tiết, Phim Hài, Tình Bạn, Tiếng...       Shen Yuan Hao   

                                                cast  
0         Luo Bin, Yin Ye Zi, Scarlet, 刘世龙（演员）, Ivan  
1  Ji Chang Wook, Kim You Jung, Angel Face, Sang-...  
2  Singto Prachaya Ruangroj, Namtan Tipnaree Weer...  
3  BoranJing, Đàm Tùng Vận, lison, Trương Bách Gi...  
4  Hae-soo Park, Jung Kyung Ho , Jung Soo Jung, J...

In [6]:
#Data co bao nhieu rows, bao nhieu columns
df.shape

(1639, 11)

In [130]:
#Nhung columns nao
df.columns

Index(['movie_title', 'kind', 'number_of_rating', 'rating_score',
       'classification', 'release_year', 'duration', 'country', 'genre',
       'director', 'cast'],
      dtype='object')

<h3> MỖI COLUMNS CÓ NHỮNG GIÁ TRỊ GÌ <h3></h3>

In [131]:
# Columns 'movie_title'
df['movie_title'].unique()

array(['Mật Tình Thất Tâm Phần 1',
       '【Lồng Tiếng】Cửa Hàng Tiện Lợi Saet Byul', 'Sắc Xanh Lãng Mạn',
       ..., 'Vua Bóng Chuyền Haikyuu - Phần 3',
       'Nghe Bảo Cô Định Tán Bố Con Tôi Mùa 4', 'Hội Trưởng Là Hầu Gái'],
      dtype=object)

In [14]:
# Columns 'kind'
df['kind'].unique()

array(['Phim bộ', 'Phim lẻ', 'Phim hoạt hình'], dtype=object)

In [15]:
# Columns 'number_of_rating'
df['number_of_rating'].unique()

array([ 14000,   1600,   4800,  56800,   8900,   4000,  50000,  11600,
        11000,  34000,  22000,   9600,   2000,   1400,   6200,  19100,
         8000,  23000,  33900,  36400,   3800,   5500,   3400,  15000,
        13000,   6000,   6500,  26000,  16900,   1500,  19600,   5100,
         1000,  29800,   1800,  54400,   1200,   8600,  60000,   7700,
        35300,   2700,  62700,  10400,   3000,  29000,  68000,  21000,
        25500,   9100,  16200,  12100,  13500,  14600,  18700,  88200,
         5400,  31100,  76800,   2600,   2100,   2400,   5000,   3300,
         3200,   9800,  16300, 262900,   5200,   2500,  20100,  27100,
         5700,  21800,   7300,  38600,   4700,  38000,  25300,   1300,
        65000,  37600,   9700,  16800,  92000,  40000,  69000, 216700,
        51000,  31000,  26300,  12300,  32600,  50200,  75000,   8800,
        22300,   3900,  12800,   6700,  20000,   6400,  90000,  17900,
        17000,   7900,   9000,   9200,  46000,  17600,  64400,  37000,
      

In [24]:
#Columns 'rating_score'
df['rating_score'].unique()

array([ 8.4,  9.4,  9.3,  9.7,  9.6,  9.2,  9. ,  8.6,  9.1,  8. ,  9.5,
        8.2,  8.8,  8.5,  8.7,  8.9,  7.6,  9.8,  9.9,  8.1,  7.8,  7.9,
       10. ,  8.3,  7.7,  7.3,  7.2,  6.5,  7.1,  7.5,  6. ,  6.2,  6.8,
        7.4,  7. ,  6.7])

In [26]:
#Columns 'genre'
df['genre'].unique()

array(['Lãng Mạn, Tổng Tài Bá Đạo, Thành Thị, Thanh Xuân',
       'Lãng Mạn, Thành Thị, Thanh Xuân, Tiếng Việt',
       'Tội Phạm, Kinh Dị, Hình Sự, Tình Bạn, Thanh Xuân, Gia Đình', ...,
       'Tiếng Nhật, Trường Học',
       'Tiếng Nhật, Cảm Hứng, Khoa Học Viễn Tưởng',
       'Thiếu niên, Tiếng Nhật, Viễn Tưởng, Nhiệt Huyết, Tình Yêu, Tiểu thuyết ngắn cải biên'],
      dtype=object)

In [5]:
#Columns 'classification'
df['classification'].unique()

array(['T13', 'T16', 'T18', 'P', 'K'], dtype=object)

In [6]:
#Columns 'release_year'
df['release_year'].unique()

array([2018, 2020, 2023, 2017, 2016, 2019, 2015, 2024, 2022, 2009, 2021,
       2013, 2012, 2011, 2014, 2010, 2004, 2008, 2005, 2006, 1991, 1984,
       1976, 1975, 1959, 1999, 2007, 1987, 1988, 1974, 1995, 1990, 1996,
       1972, 1992, 1993, 1983, 1994, 2002, 2003, 1982, 1997, 2000, 2001,
       1985, 1977, 1986, 1979, 1989], dtype=int64)

In [141]:
#Columns 'country'
df['country'].unique()

array(['Trung Quốc đại lục', 'Hàn Quốc', 'Thái Lan', 'Malaysia',
       'Đài Loan', 'Nhật Bản', 'Philippines', 'Mỹ', 'Anh', 'Hồng Kông'],
      dtype=object)

<h3> DATA CLEANING: XÓA CÁC TỪ KHÓA NGÔN NGỮ Ở CỘT GENRE & XỬ LÝ CÁC GIÁ TRỊ NA <h3>

In [5]:
#Xóa các từ khóa ngôn ngữ ở cột genre
df['genre'] = df['genre'].str.replace(r'(Thái Lan|Tiếng Việt|Tiếng Hàn|Tiếng Thái|Tiếng Mã Lai|Tiếng Phổ Thông|Tiếng Nhật|Tiếng Philippines|Tiếng Anh|Tiếng Hồng Kông|Tiếng Quảng Đông)', '', regex=True)
df['genre'] = df['genre'].str.replace(r'(\s*,\s*,\s*)', ', ', regex=True)  # Xóa một trong hai dấu ',' liên tiếp và khoảng trắng xung quanh
df['genre'] = df['genre'].str.strip(', ')  # Xóa dấu ',' và khoảng trắng ở đầu và cuối chuỗi
df.to_csv("dataIQIYI.csv")

In [6]:
#Đổi tên dataframe mới, Thêm index_col = 0 để chỉ định cột index cụ thể khi đọc và không tạo infex mới khi đọc file
df1 = pd.read_csv("dataIQIYI.csv", index_col=0)

In [7]:
#Xem số dòng, số cột trước khi xóa
df1.shape

(1639, 11)

In [8]:
df1 = df1.dropna(subset = ['genre']) #Xóa các dòng null ở cột genre
df1.to_csv("dataIQIYI.csv") 
#Xem số dòng, số cột sau khi xóa
df1.shape

(1622, 11)

<h3> XỬ LÝ GIÁ TRỊ DUPLICATE <h3>

In [9]:
df2 = df1.copy()
#Xem số dòng, số cột trước khi xóa
df2.shape

(1622, 11)

In [11]:
#Xóa các dòng duplicates
df2.drop_duplicates(inplace=True)
df2.shape #xem lại số dòng, số cột sau khi xóa

(1611, 11)

In [12]:
#Thay thế "Trung Quốc đại lục" ở cột country thành "Trung Quốc"
df2['country'] = df2['country'].str.replace(r'(Trung Quốc đại lục)', 'Trung Quốc',regex = True)
df2.to_csv("dataIQIYI.csv") 

<h3> GIẢM CHIỀU DỮ LIỆU <h3>

In [231]:
df3 = pd.read_csv("dataIQIYI.csv", index_col=0)

In [ ]:
#Hiiiii